-- ============================================================================
--  PostgreSQL 13+ — REFERENCE DDL исходных таблиц домена аудита
-- ============================================================================
--
--  PG-версия (без DISTRIBUTED BY).
--  GP-версия — в create_audit_source_tables_gp.sql.
--
--  REFERENCE — уточняется владельцем данных.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS oarb;

CREATE TABLE IF NOT EXISTS oarb.audits (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          TEXT,
    audit_type     TEXT,
    actual_date    DATE,
    auditee_entity TEXT,
    status         TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS oarb.violations (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_id       BIGINT NOT NULL,
    violation_code TEXT,
    severity       NUMERIC,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_violations_audit_id
    ON oarb.violations (audit_id);

CREATE TABLE IF NOT EXISTS oarb.audit_reports (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_id   BIGINT,
    content    TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS oarb.report_items (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id     BIGINT,
    violation_id  BIGINT,
    content       TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);