-- ============================================================================
-- oarb.violations — выявленные нарушения (REFERENCE DDL)
-- Доменная таблица навыка audit_analyzer.
-- Колонки, используемые кодом: id, audit_id, violation_code, severity.
-- FK на oarb.audits.id не объявлен (GP 6.5 не поддерживает FK).
-- Совместимость: Greenplum 6.5.
-- ============================================================================

CREATE TABLE IF NOT EXISTS oarb.violations (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    audit_id       BIGINT NOT NULL,
    report_id      BIGINT,
    item_id        BIGINT,
    violation_code TEXT,
    description    TEXT NOT NULL,
    recommendation TEXT,
    severity       TEXT NOT NULL,
    status         TEXT,
    responsible    TEXT,
    deadline       DATE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id)
)
DISTRIBUTED BY (audit_id);

COMMENT ON TABLE  oarb.violations IS 'Отклонения (нарушения, проблемы), выявленные в ходе аудита. REFERENCE — уточняется владельцем данных.';
COMMENT ON COLUMN oarb.violations.id             IS 'PK нарушения.';
COMMENT ON COLUMN oarb.violations.audit_id       IS 'FK-логически на oarb.audits.id (FK не объявлено для GP).';
COMMENT ON COLUMN oarb.violations.report_id      IS 'FK-логически на oarb.audit_reports.id.';
COMMENT ON COLUMN oarb.violations.item_id        IS 'FK-логически на oarb.report_items.id.';
COMMENT ON COLUMN oarb.violations.violation_code IS 'Код нарушения по внутреннему классификатору.';
COMMENT ON COLUMN oarb.violations.description    IS 'Подробное описание сути отклонения.';
COMMENT ON COLUMN oarb.violations.recommendation IS 'Рекомендации аудитора по устранению.';
COMMENT ON COLUMN oarb.violations.severity       IS 'Критичность (Низкая / Средняя / Высокая).';
COMMENT ON COLUMN oarb.violations.status         IS 'Текущий статус работы с нарушением.';
COMMENT ON COLUMN oarb.violations.responsible    IS 'Ответственное лицо / подразделение.';
COMMENT ON COLUMN oarb.violations.deadline       IS 'Плановая дата устранения.';
COMMENT ON COLUMN oarb.violations.created_at     IS 'Время фиксации нарушения.';
COMMENT ON COLUMN oarb.violations.updated_at     IS 'Время последнего изменения.';
