-- ============================================================================
--  PostgreSQL 13+ — таблицы для хранения векторных индексов
-- ============================================================================
--
--  PG-версия DDL (без DISTRIBUTED BY).
--  GP-версия — в create_vector_index_config_gp.sql.
--
--  Структура совместима с PG 13+. На PG 9.4-12 — может потребоваться
--  замена GENERATED BY DEFAULT AS IDENTITY на SERIAL.
-- ============================================================================

-- ============================================================================
--  Три таблицы, участвующие в семантическом поиске audit_analyzer:
--    1) oarb.vector_index_config — КОНФИГ (что строить, откуда брать)
--    2) oarb.audit_vectors       — СЫРЫЕ ЭМБЕДДИНГИ (по чанкам, с метаданными)
--    3) oarb.vector_index_store  — СЕРИАЛИЗОВАННЫЙ FAISS-ИНДЕКС (binary blob)
--
--  Конвейер: src_table → (build_vectors.py + Ollama) → audit_vectors
--         → (faiss.IndexFlatIP/IVFFlat) → vector_index_store
--         → (CacheProvider.search_vector) → результаты.
-- ============================================================================

-- 1) Конфигурация векторных индексов
CREATE TABLE IF NOT EXISTS oarb.vector_index_config (
    index_name      TEXT PRIMARY KEY,
    source_table    TEXT NOT NULL,
    src_table       TEXT NOT NULL,
    pk_column       TEXT NOT NULL DEFAULT 'id',
    content_cols    TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    embedding_cols  JSONB NOT NULL DEFAULT '[]'::JSONB,
    track_column    TEXT NOT NULL DEFAULT 'updated_at',
    enabled         BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE oarb.vector_index_config IS
    'КОНФИГУРАЦИЯ сборки векторных индексов. '
    'Описывает ЧТО строить: имя индекса, исходная таблица, колонки для content/embedding, '
    'колонка-маркер изменений. Не содержит самих векторов — только метаданные сборки. '
    'Используется tools/build_vectors.py.';
COMMENT ON COLUMN oarb.vector_index_config.index_name IS
    'PK — уникальное имя индекса (= source в audit_vectors, = source в vector_index_store).';
COMMENT ON COLUMN oarb.vector_index_config.source_table IS
    'Короткое имя для колонки source в audit_vectors. Должно совпадать с index_name.';
COMMENT ON COLUMN oarb.vector_index_config.src_table IS
    'Исходная таблица (schema.table), из которой берутся строки для эмбеддинга.';
COMMENT ON COLUMN oarb.vector_index_config.pk_column IS
    'Колонка первичного ключа в исходной таблице (для join с vector_index_store.metadata).';
COMMENT ON COLUMN oarb.vector_index_config.content_cols IS
    'TEXT[] — колонки исходной таблицы, которые попадают в audit_vectors.content (для отображения).';
COMMENT ON COLUMN oarb.vector_index_config.embedding_cols IS
    'JSONB — словарь {col_name: {chunk: bool}} — какие колонки эмбеддингить и чанковать ли.';
COMMENT ON COLUMN oarb.vector_index_config.track_column IS
    'Колонка исходной таблицы для инкрементальных обновлений (обычно updated_at).';
COMMENT ON COLUMN oarb.vector_index_config.enabled IS
    'False — пропустить индекс при сборке (например, при отключении).';
COMMENT ON COLUMN oarb.vector_index_config.created_at IS
    'Время создания записи конфига.';
COMMENT ON COLUMN oarb.vector_index_config.updated_at IS
    'Время последнего изменения конфига.';

-- 2) Хранилище сериализованных FAISS-индексов
CREATE TABLE IF NOT EXISTS oarb.vector_index_store (
    source       TEXT PRIMARY KEY,
    index_binary BYTEA NOT NULL,
    metadata     JSONB NOT NULL DEFAULT '{}'::JSONB,
    dimension    INTEGER NOT NULL DEFAULT 1024,
    vector_count INTEGER NOT NULL DEFAULT 0,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE oarb.vector_index_store IS
    'СЕРИАЛИЗОВАННЫЕ FAISS-ИНДЕКСЫ (binary blob + metadata). '
    'Одна строка на source (= index_name из vector_index_config). '
    'Строится из audit_vectors инструментами build_vectors.py: '
    'собираются все векторы одного source в faiss.IndexFlatIP/IVFFlat, '
    'сериализуются в BYTEA. Загружается lib.services.cache_provider_impl при search_vector. '
    'Контраст с audit_vectors: audit_vectors — это сырьё (по чанкам с метаданными), '
    'vector_index_store — готовый поисковый индекс (быстрый ANN).';
COMMENT ON COLUMN oarb.vector_index_store.source IS
    'PK — имя индекса (= index_name из vector_index_config, = source в audit_vectors).';
COMMENT ON COLUMN oarb.vector_index_store.index_binary IS
    'Сериализованный FAISS-индекс (pickle/bytes). Десериализуется при search_vector.';
COMMENT ON COLUMN oarb.vector_index_store.metadata IS
    'JSONB: {pk_value: {source, chunk_index, row_id, ...}} — связь FAISS-индекса с audit_vectors.';
COMMENT ON COLUMN oarb.vector_index_store.dimension IS
    'Размерность векторов (должна совпадать с embedding в audit_vectors).';
COMMENT ON COLUMN oarb.vector_index_store.vector_count IS
    'Количество векторов в индексе (контроль согласованности с audit_vectors).';
COMMENT ON COLUMN oarb.vector_index_store.updated_at IS
    'Время последней пересборки индекса.';