-- ============================================================================
-- oarb.audit_reports — акты аудиторской проверки (REFERENCE DDL)
-- Доменная таблица навыка audit_analyzer.
-- Колонки, используемые кодом: id, audit_id, report_number, report_date,
-- title, full_text.
-- Совместимость: Greenplum 6.5.
-- ============================================================================

CREATE TABLE IF NOT EXISTS oarb.audit_reports (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    audit_id      BIGINT NOT NULL,
    report_number TEXT NOT NULL,
    report_date   DATE NOT NULL,
    title         TEXT NOT NULL,
    full_text     TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id)
)
DISTRIBUTED BY (audit_id);

COMMENT ON TABLE  oarb.audit_reports IS 'Акты аудиторской проверки (оформленные документы по результатам). REFERENCE — уточняется владельцем данных.';
COMMENT ON COLUMN oarb.audit_reports.id            IS 'PK акта.';
COMMENT ON COLUMN oarb.audit_reports.audit_id      IS 'FK-логически на oarb.audits.id.';
COMMENT ON COLUMN oarb.audit_reports.report_number IS 'Номер акта (внутренняя нумерация).';
COMMENT ON COLUMN oarb.audit_reports.report_date   IS 'Дата составления акта.';
COMMENT ON COLUMN oarb.audit_reports.title         IS 'Название акта / заголовок.';
COMMENT ON COLUMN oarb.audit_reports.full_text     IS 'Полный текст акта (если без разбивки на пункты).';
COMMENT ON COLUMN oarb.audit_reports.created_at    IS 'Время создания записи.';
COMMENT ON COLUMN oarb.audit_reports.updated_at    IS 'Время последнего обновления.';
