-- ============================================================================
--  PostgreSQL 13+ — таблицы для хранения векторных индексов
-- ============================================================================
--
--  PG-версия DDL (без DISTRIBUTED BY).
--  GP-версия — в create_vector_index_config_gp.sql.
--
--  Структура совместима с PG 13+. На PG 9.4-12 — может потребоваться
--  замена GENERATED BY DEFAULT AS IDENTITY на SERIAL.
-- ============================================================================

-- Конфигурация векторных индексов
CREATE TABLE IF NOT EXISTS oarb.vector_index_config (
    index_name      TEXT PRIMARY KEY,
    source_table    TEXT NOT NULL,
    src_table       TEXT NOT NULL,
    pk_column       TEXT NOT NULL DEFAULT 'id',
    content_cols    TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    embedding_cols  JSONB NOT NULL DEFAULT '[]'::JSONB,
    track_column    TEXT NOT NULL DEFAULT 'updated_at',
    enabled         BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE oarb.vector_index_config IS
    'Конфигурация сборки векторных индексов (audit_analyzer)';
COMMENT ON COLUMN oarb.vector_index_config.index_name IS
    'Уникальное имя индекса';
COMMENT ON COLUMN oarb.vector_index_config.source_table IS
    'Короткое имя для колонки source в audit_vectors';
COMMENT ON COLUMN oarb.vector_index_config.src_table IS
    'Исходная таблица (schema.table)';
COMMENT ON COLUMN oarb.vector_index_config.pk_column IS
    'Колонка первичного ключа в исходной таблице';
COMMENT ON COLUMN oarb.vector_index_config.content_cols IS
    'Колонки для content';
COMMENT ON COLUMN oarb.vector_index_config.embedding_cols IS
    'Колонки для эмбеддинга';
COMMENT ON COLUMN oarb.vector_index_config.track_column IS
    'Колонка для ORDER BY';
COMMENT ON COLUMN oarb.vector_index_config.enabled IS
    'Индекс активен';

-- Хранилище FAISS-индексов
CREATE TABLE IF NOT EXISTS oarb.vector_index_store (
    source       TEXT PRIMARY KEY,
    index_binary BYTEA NOT NULL,
    metadata     JSONB NOT NULL DEFAULT '{}'::JSONB,
    dimension    INTEGER NOT NULL DEFAULT 1024,
    vector_count INTEGER NOT NULL DEFAULT 0,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE oarb.vector_index_store IS
    'Сериализованные FAISS-индексы';