-- ============================================================================
--  Greenplum 6.5 — таблицы для хранения векторных индексов
-- ============================================================================
--
--  Изменения относительно предыдущей версии:
--
--    1. pk_value: INTEGER → TEXT — поддержка UUID, BIGINT и других
--       типов PK в исходных таблицах (INTEGER PK тоже поддерживается
--       через TEXT-приведение).
--
--    2. id: SERIAL → BIGINT GENERATED BY DEFAULT AS IDENTITY —
--       нет переполнения на 2.1B записей (BIGINT = 9.2×10^18).
--       GP 6.5 поддерживает IDENTITY (стандарт SQL:2003).
--
--    3. DISTRIBUTED BY (index_name) для vector_index_config —
--       PK = dist key, позволяет локальные UPDATE без перемещения
--       строк между сегментами GP.
--
--    4. DISTRIBUTED REPLICATED для vector_index_store —
--       несколько строк (по одной на индекс), JOIN с vector_index_config
--       без пересылки по сегментам. Полная копия на каждом сегменте.
--
--    5. DISTRIBUTED BY (source) для audit_vectors —
--       hash-распределение по source (имени индекса), все вектора одного
--       индекса на одном сегменте GP, фильтрация без broadcast.
--
--    6. Три индекса для типовых запросов поиска вместо двух.
--
--  Совместимость: Greenplum 6.5+.
--  Для обычного PostgreSQL 13+: DISTRIBUTED BY нужно удалить
--  или закомментировать (PG не поддерживает этот синтаксис).
-- ============================================================================

-- ─────────────────────────────────────────────────────────────────────
--  Конфигурация векторных индексов
--
--  Распределение: DISTRIBUTED BY (index_name) — несколько строк
--  конфигурации. PK = dist key, UPDATE других колонок не перемещает
--  строки между сегментами GP.
-- ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS oarb.vector_index_config (
    index_name      TEXT NOT NULL,
    source_table    TEXT NOT NULL,
    src_table       TEXT NOT NULL,
    pk_column       TEXT NOT NULL DEFAULT 'id',
    content_cols    TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    embedding_cols  JSONB NOT NULL DEFAULT '[]'::JSONB,
    track_column    TEXT NOT NULL DEFAULT 'updated_at',
    enabled         BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (index_name)
)
DISTRIBUTED BY (index_name);

COMMENT ON TABLE oarb.vector_index_config IS
    'Конфигурация сборки векторных индексов (audit_analyzer)';
COMMENT ON COLUMN oarb.vector_index_config.index_name IS
    'Уникальное имя индекса (например audits_index)';
COMMENT ON COLUMN oarb.vector_index_config.source_table IS
    'Короткое имя для колонки source в audit_vectors';
COMMENT ON COLUMN oarb.vector_index_config.src_table IS
    'Исходная таблица (schema.table)';
COMMENT ON COLUMN oarb.vector_index_config.pk_column IS
    'Колонка первичного ключа в исходной таблице';
COMMENT ON COLUMN oarb.vector_index_config.content_cols IS
    'Колонки для content (текст для отображения в результатах поиска)';
COMMENT ON COLUMN oarb.vector_index_config.embedding_cols IS
    'Колонки для эмбеддинга: ["col"] или [{"column":"col","chunk":true,"chunk_size":500,"chunk_overlap":80}]';
COMMENT ON COLUMN oarb.vector_index_config.track_column IS
    'Колонка для ORDER BY при инкрементальной загрузке';
COMMENT ON COLUMN oarb.vector_index_config.enabled IS
    'Индекс активен (true = включён в build_vectors.py)';

-- ─────────────────────────────────────────────────────────────────────
--  Хранилище сериализованных FAISS-индексов
--
--  Распределение: DISTRIBUTED REPLICATED — каждый сегмент GP получает
--  полную копию. Несколько строк (по одной на индекс), экономит
--  JOIN-операции с vector_index_config.
--
--  Ограничения GP 6.5:
--    - BYTEA на сегмент: до ~1GB (для индексов <1M×1024 float32 = ~400MB OK).
--    - Для очень больших индексов (>1M векторов): нужно партиционирование
--      или внешнее хранилище. Выходит за рамки данного скрипта.
-- ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS oarb.vector_index_store (
    source       TEXT NOT NULL,
    index_binary BYTEA NOT NULL,
    metadata     JSONB NOT NULL DEFAULT '{}'::JSONB,
    dimension    INTEGER NOT NULL DEFAULT 1024,
    vector_count INTEGER NOT NULL DEFAULT 0,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (source)
)
DISTRIBUTED REPLICATED;

COMMENT ON TABLE oarb.vector_index_store IS
    'Сериализованные FAISS-индексы в BYTEA';
COMMENT ON COLUMN oarb.vector_index_store.source IS
    'Имя индекса (= oarb.vector_index_config.index_name)';
COMMENT ON COLUMN oarb.vector_index_store.index_binary IS
    'FAISS-индекс сериализованный через faiss.serialize_index';
COMMENT ON COLUMN oarb.vector_index_store.dimension IS
    'Размерность векторов (для валидации при десериализации)';
COMMENT ON COLUMN oarb.vector_index_store.vector_count IS
    'Количество векторов в индексе';