-- ============================================================================
--  PostgreSQL 13+ — таблицы для хранения векторных эмбеддингов
-- ============================================================================
--
--  PG-версия DDL (без DISTRIBUTED BY).
--  GP-версия — в create_audit_vectors_table_gp.sql.
-- ============================================================================

-- Векторные эмбеддинги
CREATE TABLE IF NOT EXISTS oarb.audit_vectors (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source         TEXT NOT NULL DEFAULT 'audits_index',
    content        TEXT,
    search_text    TEXT,
    "table"        TEXT,
    pk_value       TEXT,
    chunk_index    INTEGER NOT NULL DEFAULT 0,
    chunk_count    INTEGER NOT NULL DEFAULT 1,
    row_data       JSONB,
    embedding      REAL[] NOT NULL,
    content_hash   TEXT,
    max_src_track  TEXT,
    synced_at      TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_vectors_source_pk
    ON oarb.audit_vectors (source, pk_value);

CREATE INDEX IF NOT EXISTS idx_audit_vectors_source_synced
    ON oarb.audit_vectors (source, synced_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_vectors_source_hash
    ON oarb.audit_vectors (source, content_hash);

COMMENT ON TABLE oarb.audit_vectors IS
    'Векторные эмбеддинги для семантического поиска audit_analyzer';
COMMENT ON COLUMN oarb.audit_vectors.id IS
    'BIGINT IDENTITY (PG 10+)';
COMMENT ON COLUMN oarb.audit_vectors.source IS
    'Имя индекса';
COMMENT ON COLUMN oarb.audit_vectors.content IS
    'Текст для отображения';
COMMENT ON COLUMN oarb.audit_vectors.search_text IS
    'Текст по которому строился эмбеддинг';
COMMENT ON COLUMN oarb.audit_vectors."table" IS
    'Короткое имя исходной таблицы';
COMMENT ON COLUMN oarb.audit_vectors.pk_value IS
    'PK исходной строки (TEXT для совместимости с UUID/BIGINT/INTEGER)';
COMMENT ON COLUMN oarb.audit_vectors.chunk_index IS
    'Номер чанка';
COMMENT ON COLUMN oarb.audit_vectors.chunk_count IS
    'Общее количество чанков';
COMMENT ON COLUMN oarb.audit_vectors.row_data IS
    'Полная строка исходных данных (JSONB)';
COMMENT ON COLUMN oarb.audit_vectors.embedding IS
    'Векторный эмбеддинг float32 (REAL[])';
COMMENT ON COLUMN oarb.audit_vectors.content_hash IS
    'MD5 от search_text';
COMMENT ON COLUMN oarb.audit_vectors.max_src_track IS
    'MAX(track_column) в источнике';
COMMENT ON COLUMN oarb.audit_vectors.synced_at IS
    'Время последней синхронизации';
COMMENT ON COLUMN oarb.audit_vectors.created_at IS
    'Время создания записи в этой таблице.';