-- ============================================================================
--  PostgreSQL 13+ — REFERENCE DDL исходных таблиц домена аудита
-- ============================================================================
--
--  PG-версия (без DISTRIBUTED BY).
--  GP-версия — в create_audit_source_tables_gp.sql.
--
--  REFERENCE — уточняется владельцем данных.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS oarb;

CREATE TABLE IF NOT EXISTS oarb.audits (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          TEXT,
    audit_type     TEXT,
    planned_date   DATE,
    actual_date    DATE,
    status         TEXT,
    auditee_entity TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE oarb.audits IS 'Проверки (плановые и внеплановые аудиторские мероприятия).';
COMMENT ON COLUMN oarb.audits.id IS 'PK аудита.';
COMMENT ON COLUMN oarb.audits.title IS 'Наименование / тема проверки.';
COMMENT ON COLUMN oarb.audits.audit_type IS 'Тип проверки (плановая, внеплановая и т.д.).';
COMMENT ON COLUMN oarb.audits.planned_date IS 'Плановая дата проведения проверки.';
COMMENT ON COLUMN oarb.audits.actual_date IS 'Фактическая дата завершения проверки.';
COMMENT ON COLUMN oarb.audits.status IS 'Текущий статус проверки.';
COMMENT ON COLUMN oarb.audits.auditee_entity IS 'Проверяемый объект (юр. лицо / организация).';
COMMENT ON COLUMN oarb.audits.created_at IS 'Время создания записи.';
COMMENT ON COLUMN oarb.audits.updated_at IS 'Время последнего изменения.';

CREATE TABLE IF NOT EXISTS oarb.violations (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_id       BIGINT NOT NULL,
    report_id      BIGINT,
    item_id        BIGINT,
    violation_code TEXT,
    description    TEXT NOT NULL,
    recommendation TEXT,
    severity       TEXT NOT NULL,
    status         TEXT,
    responsible    TEXT,
    deadline       DATE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE oarb.violations IS 'Отклонения (нарушения, проблемы), выявленные в ходе аудита.';
COMMENT ON COLUMN oarb.violations.id IS 'PK нарушения.';
COMMENT ON COLUMN oarb.violations.audit_id IS 'FK на audits.id (FK не объявлено — Greenplum не поддерживает).';
COMMENT ON COLUMN oarb.violations.report_id IS 'FK на audit_reports.id.';
COMMENT ON COLUMN oarb.violations.item_id IS 'FK на report_items.id.';
COMMENT ON COLUMN oarb.violations.violation_code IS 'Код нарушения по внутреннему классификатору.';
COMMENT ON COLUMN oarb.violations.description IS 'Подробное описание сути отклонения.';
COMMENT ON COLUMN oarb.violations.recommendation IS 'Рекомендации аудитора по устранению.';
COMMENT ON COLUMN oarb.violations.severity IS 'Критичность (Низкая / Средняя / Высокая).';
COMMENT ON COLUMN oarb.violations.status IS 'Текущий статус работы с нарушением.';
COMMENT ON COLUMN oarb.violations.responsible IS 'Ответственное лицо/подразделение.';
COMMENT ON COLUMN oarb.violations.deadline IS 'Плановая дата устранения.';
COMMENT ON COLUMN oarb.violations.created_at IS 'Время фиксации нарушения.';
COMMENT ON COLUMN oarb.violations.updated_at IS 'Время последнего изменения.';

CREATE INDEX IF NOT EXISTS idx_violations_audit_id
    ON oarb.violations (audit_id);

CREATE TABLE IF NOT EXISTS oarb.audit_reports (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_id      BIGINT NOT NULL,
    report_number TEXT NOT NULL,
    report_date   DATE NOT NULL,
    title         TEXT NOT NULL,
    full_text     TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE oarb.audit_reports IS 'Акты аудиторской проверки (оформленные документы по результатам).';
COMMENT ON COLUMN oarb.audit_reports.id IS 'PK акта.';
COMMENT ON COLUMN oarb.audit_reports.audit_id IS 'FK на audits.id.';
COMMENT ON COLUMN oarb.audit_reports.report_number IS 'Номер акта (внутренняя нумерация).';
COMMENT ON COLUMN oarb.audit_reports.report_date IS 'Дата составления акта.';
COMMENT ON COLUMN oarb.audit_reports.title IS 'Название акта / заголовок.';
COMMENT ON COLUMN oarb.audit_reports.full_text IS 'Полный текст акта (если без разбивки на пункты).';
COMMENT ON COLUMN oarb.audit_reports.created_at IS 'Время создания записи.';
COMMENT ON COLUMN oarb.audit_reports.updated_at IS 'Время последнего обновления.';

CREATE TABLE IF NOT EXISTS oarb.report_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id    BIGINT NOT NULL,
    item_number  TEXT NOT NULL,
    item_title   TEXT NOT NULL,
    item_content TEXT,
    order_index  INTEGER,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE oarb.report_items IS 'Пункты (разделы) акта аудиторской проверки.';
COMMENT ON COLUMN oarb.report_items.id IS 'PK пункта.';
COMMENT ON COLUMN oarb.report_items.report_id IS 'FK на audit_reports.id.';
COMMENT ON COLUMN oarb.report_items.item_number IS 'Номер пункта (иерархия).';
COMMENT ON COLUMN oarb.report_items.item_title IS 'Название пункта.';
COMMENT ON COLUMN oarb.report_items.item_content IS 'Текст содержания пункта.';
COMMENT ON COLUMN oarb.report_items.order_index IS 'Порядковый индекс для сортировки.';
COMMENT ON COLUMN oarb.report_items.created_at IS 'Время создания.';
COMMENT ON COLUMN oarb.report_items.updated_at IS 'Время последнего обновления.';