-- ============================================================================
--  Greenplum 6.5 — таблицы для хранения векторных эмбеддингов
-- ============================================================================
--
--  Изменения относительно предыдущей версии:
--
--    1. id: SERIAL → BIGINT GENERATED BY DEFAULT AS IDENTITY.
--       SERIAL = int4 + sequence, переполняется на 2.1B записей.
--       BIGINT IDENTITY = 9.2×10^18, GP 6.5 поддерживает стандарт
--       SQL:2003 IDENTITY.
--
--    2. pk_value: INTEGER → TEXT — поддержка UUID, BIGINT и других
--       типов PK. INTEGER PK тоже поддерживается через TEXT-приведение.
--
--    3. DISTRIBUTED BY (source) — hash-распределение по имени индекса,
--       все вектора одного индекса на одном сегменте GP, фильтрация
--       WHERE source = ? без broadcast.
--
--    4. Индекс idx_audit_vectors_source_synced — для запросов
--       "последние синхронизации" (синхронизация админкой).
--
--    5. Индекс idx_audit_vectors_source_hash — для дедупликации
--       при пересборке (один content_hash на (source, hash)).
--
--  Совместимость: Greenplum 6.5+.
--  Для обычного PostgreSQL 13+: DISTRIBUTED BY нужно удалить.
-- ============================================================================

-- ─────────────────────────────────────────────────────────────────────
--  Векторные эмбеддинги
--
--  embedding: REAL[] (float32 массив). GP 6.5 поддерживает с ограничением
--  ~1GB на массив на сегмент (для 1024-dim = ~1M векторов на сегмент).
--  Для большинства случаев (10k-100k векторов) — OK.
--
--  Распределение: DISTRIBUTED BY (source) — JOIN с agent_vector_index_store
--  (REPLICATED) делается локально, фильтрация по source без broadcast.
-- ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS oarb.audit_vectors (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    source         TEXT NOT NULL DEFAULT 'audits_index',
    content        TEXT,
    search_text    TEXT,
    "table"        TEXT,
    pk_value       TEXT,                              -- BIGINT/UUID/INTEGER через TEXT
    chunk_index    INTEGER NOT NULL DEFAULT 0,
    chunk_count    INTEGER NOT NULL DEFAULT 1,
    row_data       JSONB,
    embedding      REAL[] NOT NULL,                   -- float32 массив (GP 6.5 OK до 1GB)
    content_hash   TEXT,
    max_src_track  TEXT,
    synced_at      TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id)
)
DISTRIBUTED BY (source);

-- Индексы для типовых запросов поиска (GP 6.5 поддерживает btree).
-- Запросы: WHERE source = ? AND pk_value = ? (lookup по первичному ключу)
CREATE INDEX IF NOT EXISTS idx_audit_vectors_source_pk
    ON oarb.audit_vectors (source, pk_value);

-- Запросы: WHERE source = ? ORDER BY synced_at DESC (последние изменения)
CREATE INDEX IF NOT EXISTS idx_audit_vectors_source_synced
    ON oarb.audit_vectors (source, synced_at DESC);

-- Запросы: дедупликация при пересборке (по content_hash)
CREATE INDEX IF NOT EXISTS idx_audit_vectors_source_hash
    ON oarb.audit_vectors (source, content_hash);

COMMENT ON TABLE oarb.audit_vectors IS
    'Векторные эмбеддинги для семантического поиска audit_analyzer';
COMMENT ON COLUMN oarb.audit_vectors.id IS
    'BIGINT IDENTITY (GP 6.5 / PG 10+)';
COMMENT ON COLUMN oarb.audit_vectors.source IS
    'Имя индекса (= public.agent_vector_index_config.index_name)';
COMMENT ON COLUMN oarb.audit_vectors.content IS
    'Текст для отображения в результатах поиска';
COMMENT ON COLUMN oarb.audit_vectors.search_text IS
    'Текст по которому строился эмбеддинг';
COMMENT ON COLUMN oarb.audit_vectors."table" IS
    'Короткое имя исходной таблицы (= source_table в конфиге)';
COMMENT ON COLUMN oarb.audit_vectors.pk_value IS
    'PK исходной строки (TEXT — для совместимости с UUID/BIGINT/INTEGER)';
COMMENT ON COLUMN oarb.audit_vectors.chunk_index IS
    'Номер чанка (0-based), если документ разбит на несколько векторов';
COMMENT ON COLUMN oarb.audit_vectors.chunk_count IS
    'Общее количество чанков для данного документа';
COMMENT ON COLUMN oarb.audit_vectors.row_data IS
    'Полная строка исходных данных (JSONB)';
COMMENT ON COLUMN oarb.audit_vectors.embedding IS
    'Векторный эмбеддинг float32 размерности 1024 (REAL[])';
COMMENT ON COLUMN oarb.audit_vectors.content_hash IS
    'MD5 от search_text — для обнаружения изменений без переэмбеддинга';
COMMENT ON COLUMN oarb.audit_vectors.max_src_track IS
    'MAX(track_column) в источнике на момент синхронизации';
COMMENT ON COLUMN oarb.audit_vectors.synced_at IS
    'Время последней синхронизации с исходной таблицей';