-- ============================================================================
-- oarb.report_items — пункты (разделы) акта аудиторской проверки (REFERENCE DDL)
-- Доменная таблица навыка audit_analyzer.
-- Совместимость: Greenplum 6.5.
-- ============================================================================

CREATE TABLE IF NOT EXISTS oarb.report_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    report_id    BIGINT NOT NULL,
    item_number  TEXT NOT NULL,
    item_title   TEXT NOT NULL,
    item_content TEXT,
    order_index  INTEGER,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id)
)
DISTRIBUTED BY (report_id);

COMMENT ON TABLE  oarb.report_items IS 'Пункты (разделы) акта аудиторской проверки. REFERENCE — уточняется владельцем данных.';
COMMENT ON COLUMN oarb.report_items.id           IS 'PK пункта.';
COMMENT ON COLUMN oarb.report_items.report_id    IS 'FK-логически на oarb.audit_reports.id.';
COMMENT ON COLUMN oarb.report_items.item_number  IS 'Номер пункта (иерархия).';
COMMENT ON COLUMN oarb.report_items.item_title   IS 'Название пункта.';
COMMENT ON COLUMN oarb.report_items.item_content IS 'Текст содержания пункта.';
COMMENT ON COLUMN oarb.report_items.order_index  IS 'Порядковый индекс для сортировки.';
COMMENT ON COLUMN oarb.report_items.created_at   IS 'Время создания.';
COMMENT ON COLUMN oarb.report_items.updated_at   IS 'Время последнего обновления.';

DO $body$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes
        WHERE schemaname = 'oarb' AND indexname = 'idx_report_items_report_id'
    ) THEN
        CREATE INDEX idx_report_items_report_id
            ON oarb.report_items (report_id);
    END IF;
END
$body$;
