-- ============================================================================
--  Greenplum 6.5 — REFERENCE-схема исходных таблиц домена аудита
-- ============================================================================
--
--  Изменения относительно предыдущей версии:
--
--    1. Все ID — BIGINT GENERATED BY DEFAULT AS IDENTITY вместо SERIAL
--       (нет переполнения на 2.1B, стандарт SQL:2003).
--
--    2. DISTRIBUTED BY добавлен для всех таблиц:
--       - oarb.audits: DISTRIBUTED BY (id) — равномерное распределение.
--       - oarb.violations: DISTRIBUTED BY (audit_id) — все нарушения
--         одного аудита на одном сегменте (ускоряет JOIN).
--       - oarb.audit_reports: DISTRIBUTED BY (audit_id) — то же.
--       - oarb.report_items: DISTRIBUTED BY (report_id) — то же.
--
--    3. pgcrypto не требуется — UUID не используется (всё через BIGINT).
--       gen_random_uuid() доступен с PG 13+, GP 6.5 (PG 9.4 ядро) — нет.
--
--    REFERENCE — уточняется владельцем данных.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS oarb;

-- ─────────────────────────────────────────────────────────────────────
--  oarb.audits — аудиторские проверки
--  Колонки, используемые кодом: id, title, audit_type, actual_date,
--  auditee_entity, status
-- ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS oarb.audits (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          TEXT,
    audit_type     TEXT,
    actual_date    DATE,
    auditee_entity TEXT,
    status         TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
)
DISTRIBUTED BY (id);

COMMENT ON COLUMN oarb.audits.audit_type IS
    'Тип проверки (например, "финансовый")';
COMMENT ON COLUMN oarb.audits.actual_date IS
    'Дата фактического проведения проверки';
COMMENT ON COLUMN oarb.audits.auditee_entity IS
    'Проверяемый объект (название организации)';
COMMENT ON COLUMN oarb.audits.status IS
    'Статус проверки (например, "закрыто"/"completed")';
COMMENT ON COLUMN oarb.audits.updated_at IS
    'Отметка изменений — используется для проверки свежести DuckDB-кеша';

-- ─────────────────────────────────────────────────────────────────────
--  oarb.violations — выявленные нарушения
--  Колонки, используемые кодом: id, audit_id, violation_code, severity
-- ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS oarb.violations (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_id       BIGINT NOT NULL,
    violation_code TEXT,
    severity       NUMERIC,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
)
DISTRIBUTED BY (audit_id);

CREATE INDEX IF NOT EXISTS idx_violations_audit_id
    ON oarb.violations (audit_id);

COMMENT ON COLUMN oarb.violations.audit_id IS
    'Связь с проверкой (oarb.audits.id)';
COMMENT ON COLUMN oarb.violations.violation_code IS
    'Код/тип нарушения (например, "финансовые")';
COMMENT ON COLUMN oarb.violations.severity IS
    'Серьёзность нарушения (число)';

-- ─────────────────────────────────────────────────────────────────────
--  oarb.audit_reports — отчёты по проверкам (опциональная таблица)
-- ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS oarb.audit_reports (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_id   BIGINT,
    content    TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)
DISTRIBUTED BY (audit_id);

-- ─────────────────────────────────────────────────────────────────────
--  oarb.report_items — строки/пункты отчётов (опциональная таблица)
-- ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS oarb.report_items (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id     BIGINT,
    violation_id  BIGINT,
    content       TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
)
DISTRIBUTED BY (report_id);