"""Модель событий платформы: словарь, конверт, писатель.

Один словарь типов на агента и MCP. Событие, смысл которого непонятен из
самого имени, не пишется вовсе: журнал, который читают через `history_search`,
должен оставаться разбираемым без знания внутренностей каждой capability.
"""

from .models import (
    COMPONENT_TOOL_EXECUTION,
    DEFAULT_MIN_LEVEL,
    DIAGNOSTIC_LEVEL,
    JOURNAL_FIELDS,
    LEVEL_RANKS,
    LEVELS,
    SOURCE_ENTERPRISE_MCP,
    SOURCE_NANOBOT,
    AgentEvent,
    is_at_least,
    is_diagnostic,
    level_rank,
    normalize_level,
    with_identity,
)
from .types import (
    AGENT_COMPACTED,
    AGENT_COMPLETED,
    AGENT_DEGRADED,
    AGENT_DELIVERED,
    AGENT_FAILED,
    AGENT_RECEIVED,
    AGENT_RESPONDED,
    AGENT_STARTED,
    ALLOWED_PREFIXES,
    ARTIFACT_CREATED,
    ARTIFACT_READ,
    EVENT_TYPES,
    LLM_COMPLETED,
    LLM_EXCHANGED,
    LLM_FAILED,
    LLM_REQUESTED,
    PROBE_EVENT_NAMES,
    PROBE_EVENT_PREFIXES,
    QUALITY_CHECK,
    TOOL_COMPLETED,
    TOOL_FAILED,
    TOOL_STARTED,
    TOOL_SUPPRESSED,
    TOOL_TIMEOUT,
    UnknownEventType,
    is_known,
    is_probe_event_type,
    require_known,
)
from .writer import (
    ACCEPTED,
    DROPPED,
    NO_SINK,
    REJECTED,
    SUPPRESSED,
    EventSink,
    EventWriter,
)

__all__ = [
    "ACCEPTED",
    "AGENT_COMPLETED",
    "AGENT_COMPACTED",
    "AGENT_DEGRADED",
    "AGENT_DELIVERED",
    "AGENT_FAILED",
    "AGENT_RECEIVED",
    "AGENT_RESPONDED",
    "AGENT_STARTED",
    "ALLOWED_PREFIXES",
    "ARTIFACT_CREATED",
    "ARTIFACT_READ",
    "AgentEvent",
    "COMPONENT_TOOL_EXECUTION",
    "DEFAULT_MIN_LEVEL",
    "DIAGNOSTIC_LEVEL",
    "DROPPED",
    "EVENT_TYPES",
    "EventSink",
    "EventWriter",
    "JOURNAL_FIELDS",
    "LEVELS",
    "LEVEL_RANKS",
    "LLM_COMPLETED",
    "LLM_EXCHANGED",
    "LLM_FAILED",
    "LLM_REQUESTED",
    "NO_SINK",
    "PROBE_EVENT_NAMES",
    "PROBE_EVENT_PREFIXES",
    "QUALITY_CHECK",
    "REJECTED",
    "SOURCE_ENTERPRISE_MCP",
    "SOURCE_NANOBOT",
    "SUPPRESSED",
    "TOOL_COMPLETED",
    "TOOL_FAILED",
    "TOOL_STARTED",
    "TOOL_SUPPRESSED",
    "TOOL_TIMEOUT",
    "UnknownEventType",
    "is_at_least",
    "is_diagnostic",
    "is_known",
    "is_probe_event_type",
    "level_rank",
    "normalize_level",
    "require_known",
    "with_identity",
]
