-- ============================================================================
-- МЁРТВЫЙ КОД — этот DDL больше не применяется. Удалить файл.
--
-- После change ``remove-vector-index-store`` persisted FAISS-кеш в
-- ``public.agent_vector_index_store`` удалён (см. migration
-- V003__drop_vector_index_store.sql). FAISS собирается в памяти из
-- DuckDB-снимка capability ``data``.
--
-- Файл не исполняется: ``tools/migrate.py`` обходит только
-- ``sql/migrations/V*.sql``, а этот файл лежит в ``sql/vectors/``.
--
-- Удалить вручную: git rm sql/vectors/create_vector_index_store.sql
-- ============================================================================
