-- ============================================================================
--  Миграция v2.0 — PostgreSQL 13+
-- ============================================================================
--
--  PG-версия миграции (без DISTRIBUTED BY).
--  GP-версия — в migrate_vectors_v2_gp.sql.
--
--  Изменения:
--    1. oarb.audit_vectors.pk_value: INTEGER → TEXT (поддержка UUID/BIGINT)
--    2. oarb.audit_vectors.id: SERIAL → BIGINT IDENTITY
--    3. Новые индексы source_synced и source_hash
--
--  КРИТИЧНО: миграция удаляет ВСЕ данные в oarb.audit_vectors
--  и public.agent_vector_index_store. После ОБЯЗАТЕЛЬНО:
--      python tools/build_vectors.py --full-rebuild
-- ============================================================================

BEGIN;

DROP INDEX IF EXISTS oarb.idx_audit_vectors_source;
DROP INDEX IF EXISTS oarb.idx_audit_vectors_pk;
DROP TABLE IF EXISTS public.agent_vector_index_store CASCADE;
DROP TABLE IF EXISTS oarb.audit_vectors CASCADE;
DROP TABLE IF EXISTS public.agent_vector_index_config CASCADE;

CREATE TABLE IF NOT EXISTS public.agent_vector_index_config (
    index_name      TEXT PRIMARY KEY,
    source_table    TEXT NOT NULL,
    src_table       TEXT NOT NULL,
    pk_column       TEXT NOT NULL DEFAULT 'id',
    content_cols    TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    embedding_cols  JSONB NOT NULL DEFAULT '[]'::JSONB,
    track_column    TEXT NOT NULL DEFAULT 'updated_at',
    enabled         BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.agent_vector_index_store (
    source       TEXT PRIMARY KEY,
    index_binary BYTEA NOT NULL,
    metadata     JSONB NOT NULL DEFAULT '{}'::JSONB,
    dimension    INTEGER NOT NULL DEFAULT 1024,
    vector_count INTEGER NOT NULL DEFAULT 0,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS oarb.audit_vectors (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source         TEXT NOT NULL DEFAULT 'audits_index',
    content        TEXT,
    search_text    TEXT,
    "table"        TEXT,
    pk_value       TEXT,
    chunk_index    INTEGER NOT NULL DEFAULT 0,
    chunk_count    INTEGER NOT NULL DEFAULT 1,
    row_data       JSONB,
    embedding      REAL[] NOT NULL,
    content_hash   TEXT,
    max_src_track  TEXT,
    synced_at      TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_vectors_source_pk
    ON oarb.audit_vectors (source, pk_value);
CREATE INDEX IF NOT EXISTS idx_audit_vectors_source_synced
    ON oarb.audit_vectors (source, synced_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_vectors_source_hash
    ON oarb.audit_vectors (source, content_hash);

INSERT INTO public.agent_vector_index_config
    (index_name, source_table, src_table, pk_column,
     content_cols, embedding_cols, track_column, enabled)
VALUES
    ('audits_index', 'audits', 'oarb.audits', 'id',
     ARRAY['title', 'audit_type', 'auditee_entity', 'status']::TEXT[],
     '["title", "audit_type", "auditee_entity", "status"]'::JSONB,
     'updated_at', true),
    ('violations_index', 'violations', 'oarb.violations', 'id',
     ARRAY['description', 'recommendation', 'violation_code', 'severity']::TEXT[],
     '[{"column": "description", "chunk": true, "chunk_size": 500, "chunk_overlap": 80}, "violation_code"]'::JSONB,
     'updated_at', true),
    ('audit_reports_index', 'audit_reports', 'oarb.audit_reports', 'id',
     ARRAY['full_text', 'title', 'report_number', 'report_date']::TEXT[],
     '[{"column": "full_text", "chunk": true, "chunk_size": 500, "chunk_overlap": 80}, "title"]'::JSONB,
     'updated_at', true)
ON CONFLICT (index_name) DO UPDATE SET
    source_table   = EXCLUDED.source_table,
    src_table      = EXCLUDED.src_table,
    pk_column      = EXCLUDED.pk_column,
    content_cols   = EXCLUDED.content_cols,
    embedding_cols = EXCLUDED.embedding_cols,
    track_column   = EXCLUDED.track_column,
    enabled        = EXCLUDED.enabled,
    updated_at     = NOW();

COMMIT;