-- ============================================================================
--  Миграция v2.0 — Greenplum 6.5 / PostgreSQL 13+
-- ============================================================================
--
--  Изменения, требующие ручной миграции:
--
--    1. oarb.audit_vectors.pk_value: INTEGER → TEXT
--       Причина: поддержка UUID, BIGINT и других типов PK.
--       GP 6.5 (PostgreSQL 9.4 ядро) при переходе на TEXT через USING
--       требует явного приведения: USING pk_value::TEXT.
--
--    2. oarb.audit_vectors.id: SERIAL → BIGINT IDENTITY
--       Причина: SERIAL = int4 + sequence, переполняется на 2.1B.
--       GP 6.5 / PG 10+ поддерживают IDENTITY (стандарт SQL:2003).
--
--    3. Добавление DISTRIBUTED BY (GP 6.5+).
--
--    4. Новые индексы idx_audit_vectors_source_synced и
--       idx_audit_vectors_source_hash.
--
--  КРИТИЧНО: миграция удаляет ВСЕ данные в oarb.audit_vectors и
--  public.agent_vector_index_store. После миграции ОБЯЗАТЕЛЬНО:
--
--      python tools/build_vectors.py --full-rebuild
--
--  Это идемпотентная миграция: запускать можно несколько раз.
--
--  Применение (GP 6.5):
--      psql "$DATABASE_URL" -f sql/migrations/migrate_vectors_v2_gp.sql
--      python tools/build_vectors.py --full-rebuild
--
--  Применение (PG 13+):
--      1. Удалить строки с DISTRIBUTED BY
--      2. Удалить строки с USING для ALTER TYPE (PG не требует USING
--         при INTEGER → TEXT, автоматическое приведение работает)
-- ============================================================================

BEGIN;

-- ─────────────────────────────────────────────────────────────────────
--  Шаг 1: бэкап не нужен — мы удаляем данные
--  Если нужен бэкап, выполните ДО этой миграции:
--      pg_dump -t oarb.audit_vectors -t public.agent_vector_index_store \
--          -t public.agent_vector_index_config > backup_vectors.sql
-- ─────────────────────────────────────────────────────────────────────

-- ─────────────────────────────────────────────────────────────────────
--  Шаг 2: удаление старых таблиц (если структура старая)
--  Сохраняем данные через pg_dump перед этой миграцией если нужны.
-- ─────────────────────────────────────────────────────────────────────

-- Удалить старые индексы (если есть) — иначе ALTER может упасть
DROP INDEX IF EXISTS oarb.idx_audit_vectors_source;
DROP INDEX IF EXISTS oarb.idx_audit_vectors_pk;

-- Удалить таблицы — после ALTER TYPE они всё равно будут пересозданы.
-- Это безопаснее, чем ALTER на месте (GP 6.5 требует пересоздания
-- для изменения IDENTITY-колонок и distribution policy).
DROP TABLE IF EXISTS public.agent_vector_index_store CASCADE;
DROP TABLE IF EXISTS oarb.audit_vectors CASCADE;
DROP TABLE IF EXISTS public.agent_vector_index_config CASCADE;

-- ─────────────────────────────────────────────────────────────────────
--  Шаг 3: пересоздание с новой структурой
--  Содержимое скопировано из create_vector_index_config_gp.sql
--  и create_audit_vectors_table_gp.sql.
--  Идемпотентно: CREATE TABLE IF NOT EXISTS.
-- ─────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.agent_vector_index_config (
    index_name      TEXT NOT NULL,
    source_table    TEXT NOT NULL,
    src_table       TEXT NOT NULL,
    pk_column       TEXT NOT NULL DEFAULT 'id',
    content_cols    TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    embedding_cols  JSONB NOT NULL DEFAULT '[]'::JSONB,
    track_column    TEXT NOT NULL DEFAULT 'updated_at',
    enabled         BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (index_name)
)
DISTRIBUTED BY (index_name);

CREATE TABLE IF NOT EXISTS public.agent_vector_index_store (
    source       TEXT NOT NULL,
    index_binary BYTEA NOT NULL,
    metadata     JSONB NOT NULL DEFAULT '{}'::JSONB,
    dimension    INTEGER NOT NULL DEFAULT 1024,
    vector_count INTEGER NOT NULL DEFAULT 0,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (source)
)
DISTRIBUTED REPLICATED;

CREATE TABLE IF NOT EXISTS oarb.audit_vectors (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    source         TEXT NOT NULL DEFAULT 'audits_index',
    content        TEXT,
    search_text    TEXT,
    "table"        TEXT,
    pk_value       TEXT,
    chunk_index    INTEGER NOT NULL DEFAULT 0,
    chunk_count    INTEGER NOT NULL DEFAULT 1,
    row_data       JSONB,
    embedding      REAL[] NOT NULL,
    content_hash   TEXT,
    max_src_track  TEXT,
    synced_at      TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id)
)
DISTRIBUTED BY (source);

CREATE INDEX IF NOT EXISTS idx_audit_vectors_source_pk
    ON oarb.audit_vectors (source, pk_value);

CREATE INDEX IF NOT EXISTS idx_audit_vectors_source_synced
    ON oarb.audit_vectors (source, synced_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_vectors_source_hash
    ON oarb.audit_vectors (source, content_hash);

-- ─────────────────────────────────────────────────────────────────────
--  Шаг 4: перерегистрация дефолтных индексов
-- ─────────────────────────────────────────────────────────────────────

INSERT INTO public.agent_vector_index_config
    (index_name, source_table, src_table, pk_column,
     content_cols, embedding_cols, track_column, enabled)
VALUES
    ('audits_index', 'audits', 'oarb.audits', 'id',
     ARRAY['title', 'audit_type', 'auditee_entity', 'status']::TEXT[],
     '["title", "audit_type", "auditee_entity", "status"]'::JSONB,
     'updated_at', true),
    ('violations_index', 'violations', 'oarb.violations', 'id',
     ARRAY['description', 'recommendation', 'violation_code', 'severity']::TEXT[],
     '[{"column": "description", "chunk": true, "chunk_size": 500, "chunk_overlap": 80}, "violation_code"]'::JSONB,
     'updated_at', true),
    ('audit_reports_index', 'audit_reports', 'oarb.audit_reports', 'id',
     ARRAY['full_text', 'title', 'report_number', 'report_date']::TEXT[],
     '[{"column": "full_text", "chunk": true, "chunk_size": 500, "chunk_overlap": 80}, "title"]'::JSONB,
     'updated_at', true)
ON CONFLICT (index_name) DO UPDATE SET
    source_table   = EXCLUDED.source_table,
    src_table      = EXCLUDED.src_table,
    pk_column      = EXCLUDED.pk_column,
    content_cols   = EXCLUDED.content_cols,
    embedding_cols = EXCLUDED.embedding_cols,
    track_column   = EXCLUDED.track_column,
    enabled        = EXCLUDED.enabled,
    updated_at     = NOW();

COMMIT;

-- ─────────────────────────────────────────────────────────────────────
--  После миграции ОБЯЗАТЕЛЬНО:
--    python tools/build_vectors.py --full-rebuild
--
--  Это пересоздаст все 120+ векторов и FAISS-индексы.
--  Без этого поиск через --mode vector вернёт пустой результат.
-- ─────────────────────────────────────────────────────────────────────